"""Added one-to-one relationship between author_profiles and users tables

Revision ID: 438222274ec5
Revises: a34b0ecc0bd4
Create Date: 2026-04-29 14:50:46.552169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '438222274ec5'
down_revision: Union[str, Sequence[str], None] = 'a34b0ecc0bd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author_profiles', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'author_profiles', ['id'])
    op.create_unique_constraint(None, 'author_profiles', ['user_id'])
    op.create_foreign_key(None, 'author_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'author_profiles', type_='foreignkey')
    op.drop_constraint(None, 'author_profiles', type_='unique')
    op.drop_constraint(None, 'author_profiles', type_='unique')
    op.drop_column('author_profiles', 'user_id')
    # ### end Alembic commands ###
