"""Create Author Profile Table

Revision ID: a34b0ecc0bd4
Revises: 
Create Date: 2026-04-29 13:48:15.499235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a34b0ecc0bd4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author_profiles',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('pen_name', sqlmodel.sql.sqltypes.AutoString(
                        length=100), nullable=True),
                    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(
                        length=500), nullable=True),
                    sa.Column('twitter_handle', sqlmodel.sql.sqltypes.AutoString(
                        length=50), nullable=True),
                    sa.Column('linkedin_url', sqlmodel.sql.sqltypes.AutoString(
                        length=500), nullable=True),
                    sa.Column('posts_count', sa.Integer(), nullable=False),
                    sa.Column('is_featured', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )
    op.create_unique_constraint(None, 'users', ['id'])
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'email_verified_at')
    op.drop_column('users', 'last_login_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login_at',
                  postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('email_verified_at',
                  postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(),
                  autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_table('author_profiles')
    # ### end Alembic commands ###
